Repository seedn-corp/viz-playground-web-fe, pull requests merged in 2025-09, with the labels that each got.

#4 chore: eslint & prettier 설정 추가
  .prettierrc
  eslint.config.js
  package.json
  src/Router.tsx
  src/atoms/dashboard/index.ts
  src/components/chart/ChartArea/index.tsx
  src/components/chart/FileUploader/index.tsx
  src/components/chart/Popover/index.tsx
  src/components/chart/Select/index.tsx
  src/components/chart/Select/types.ts
  src/components/chart/Separator/index.tsx
  src/components/chart/SideBar/index.tsx
  src/components/chart/YAxisMultipleSelect/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/WidgetAddDialog/styles.ts
  src/components/common/charts/AreaChart/index.tsx
  src/components/common/charts/BarChart/index.tsx
  src/components/common/charts/LineChart/index.tsx
  src/components/common/charts/PieChart/index.tsx
  src/components/dashboard/DashboardGrid/index.tsx
  src/components/widgets/WidgetSlot/RegistryCore.ts
  src/components/widgets/WidgetSlot/index.tsx
  src/main.tsx
  src/pages/chart/index.tsx
  src/pages/home/index.tsx
  vite.config.ts
  yarn.lock
Labels: ⚙ Chore

#14 fix: API url 수정 및 타입 수정
  src/apis/widgets/index.ts
  src/types/widgets/index.ts
Labels: 🔧 Fix

#26 fix: 위젯 편집하다 취소 시에 원래대로 돌아가도록 처리
  src/components/dashboard/DashboardGrid/index.tsx
Labels: 🔧 Fix

#40 feat: 사이드바 고정/해제 shortcut key 추가 (Cmd + B (Mac) / Ctrl + B (Windows))
  src/components/dashboard/DashboardSidebar/index.tsx
  src/pages/dashboard/Layout.tsx
Labels: ✨ Feat

#41 feat: 대시보드 > Table 위젯 추가 > 엑셀 데이터 다운로드 기능 추가
  src/pages/table/index.tsx
  src/pages/table/styles.ts
Labels: ✨ Feat

#49 style: dialog와 icon 스타일 변경
  src/components/common/Dialog/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/WidgetAddDialog/index.tsx
  src/components/dashboard/DashboardGrid/index.tsx
  src/components/dashboard/DashboardGrid/styles.ts
  src/components/dashboard/DashboardSidebar/index.tsx
  src/pages/dashboard/Layout.tsx
  src/pages/dashboard/detail/index.tsx
Labels: 🎨 Style

#56 fix: 위젯 없는 경우 위쪽에 ResponsiveGridLayout 기본 높이 잡히는 오류 수정
  src/components/dashboard/DashboardGrid/index.tsx
Labels: 🔧 Fix
